// 45 minutes
:revealjs_totalTime: 2700

= The Original Sin of Scala Ecosystems

Mateusz Kubuszok

== About me

[%step]
* breaking things in Scala for 7+ years
* breaking things for money for 10 years
* breaking things for fun for 18(?) years
* a little bit of open source
* blog at https://kubuszok.com[Kubuszok.com]
* niche https://leanpub.com/jvm-scala-book[Things you need to know about JVM (that matter in Scala)] ebook

[NOTE.speaker]
--
Every presentation should start with some excuse, why you even are here
--

== Agenda

[%step]
* a (de)motivating example
* more examples from history
* pattern?
* what can we do about it

== A (de)motivating example

=== My idea

[%step]
* OSS clone of Reddit
* Scala 2.13
* Cats + Cats Effect 2 + FS2 + Http4s
* Monix as IO, TaskLocal for MDC
* Tapir
* Jsoniter
* Scala Newtype

=== !

[%step]
* March 2021 - last commit
* everything works
* September 2022 - updated dependencies
* migration took about 2-3 weeks

=== Why?

=== Cats Effect 2 to 3

=== !

[source, scala]
--
def myModule[F[_] : ConcurrentEffect
                  : ContextShift
                  : Timer]: Resource[F, MyModule] = ...

someIO.unsafeRunSync()
--

[source, scala]
--
def myModule[F[_]: Async]: Resource[F, MyModule] = ...

import cats.effect.unsafe.implicits.global
someIO.unsafeRunSync()
--

[NOTE.speaker]
--
Nice for new users, worse for existing users.
--

=== !

Also:

[%step]
* forced updated of libraries which depended on CE: FS2, Http4s, Doobie
* there is no Monix for Cats Effect 3 ATM

=== Monix and ``Local``

=== !

[source, scala]
--
// Based on https://olegpy.com/better-logging-monix-1/
final class MonixMDCAdapter extends LogbackMDCAdapter {
  private val map = monix.execution.misc.Local(
    java.util.Collections.emptyMap[String, String]())
  // methods delegating to map
}
object MonixMDCAdapter {
  def configure(): Unit = {
    val field = classOf[org.slf4j.MDC]
      .getDeclaredField("mdcAdapter")
    field.setAccessible(true)
    field.set(null, new MonixMDCAdapter)
  }
}
--

[source, scala]
--
// set up Logback
MonixMDCAdapter.configure()
// propagating changes to Local within Task
task.executeWithOptions(_.enableLocalContextPropagation)
--

=== !

[source, scala]
--
object IOGlobal {
  private val threadLocal = ThreadLocal.withInitial(
    () => Map.empty[IOLocal[_], Any]
  )
  // IOLocalHack.get : IO[Map.empty[IOLocal[_], Any]]
  def propagateState[A](thunk: => IO[A]): IO[A] =
    IOLocalHack.get.flatMap { state =>
      threadLocal.set(state); thunk }
}
--

[source, scala]
--
def configureAsync(tc: Async[IO]) = new Async[IO] {
  // extract IOLocal and set it in threadLocal
  // in every operation which might use it
  def suspend[A](hint: Sync.Type)(thunk: => A) =
    tc.suspend(hint)(propagateState(tc.pure(thunk))).flatten
  def handleErrorWith[A](fa: IO[A])(f: Throwable => IO[A]) =
    tc.handleErrorWith(fa)(e => propagateState(f(e)))
  def flatMap[A, B](fa: IO[A])(f: A => IO[B]) =
    tc.flatMap(fa)(a => propagateState(f(a)))
  def tailRecM[A, B](a: A)(f: A => IO[Either[A, B]]) =
    tc.tailRecM(a)(b => propagateState(f(b)))
  // and plain redirect to tc for everythin else
}
--

=== FS2 Kafka

[source, scala]
--
type EventBusProducer[F[_], Event] = Pipe[
  F,
  (UUID, Event),
  ProducerResult[UUID, Event, Unit]
]
--

[source, scala]
--
// changed the order of parameters in ProducerResult
type EventBusProducer[F[_], Event] = Pipe[
  F,
  (UUID, Event),
  ProducerResult[Unit, UUID, Event] // <-- here
]
--

=== Http4s

[source, scala]
--
import org.http4s.server.blaze.BlazeServerBuilder
import org.http4s.util.{ CaseInsensitiveString => CIString }
--

[source, scala]
--
// Blaze moved to a separate dependency
import org.http4s.blaze.server.BlazeServerBuilder
// CIString became deprecated alias
import org.typelevel.ci.CIString
--

=== !

TODO

* Tapir 0.x to 1.x
* added new type parameter (representing auth)
* changed the format of configs

== Other Examples from History

=== Scala 2.12 to 2.13

TODO

=== Happy experiments

[%step]
* ``scala-parallel-collections``
* ``scala-parser-combinators``
* ``scala-continuations``


[NOTE.speaker]
--
Still present in old textbooks. Usually, you move proven things into standard library, not kick them off inside it and then move out.
--

=== Neverending 0.x version

[%step]
* TODO

=== Major version update

[%step]
* TODO

=== Monad of the season

[%step]
* TODO

== What Can We Do About It?

== Summary

== Thank You!


